### ISSUE TITLE
XML Import is not working

### ISSUE THREAD

**Issue by Weedshaker** [Bunnyfield/l10nmgr#5]
Hello,

I have been using l10n manager in older versions. And its nice that you try to bring it to v7. Though, I just wasn't able to make it work. Export works fine but after importing, nothing happens. No alternative language entry is created. Is there anything I am missing?

**Comment by Bunnyfield** [comment]
You might have noticed, that the branch for the "old" 5.0 version, which is compatible to TYPO3 6.2 only, has been created just yesterday.

Master will be updated soon to be compatible with CMS 7 only, which will then be released as 7.0 version. - So currently full CMS 7 compatibility is WIP and not yet available on github or TER, but sponsoring is always welcome and might speed up the process a bit :-)

In your special case it might help to somehow reenable 
$GLOBALS['TYPO3_CONF_VARS']['SYS']['form_enctype'] - which has been removed in CMS 7 but is necessary for <form> tags in current l10nmgr code here on github. Otherwise you won't get any files.

**Comment by Weedshaker** [comment]
I tried the form_enctype but didn't help. Online Translation works though. So lets hope that you get this fixed asap.

Send me your donation link. I will consider this, though I haven't made any cash on this project, certainly not until the translation works flawlessly as it used to do in older versions.

Cheers

**Comment by Bunnyfield** [comment]
Thanks for considering it. You can use payment@cybercraft.info for donations and if you send us your address and tax data as well, you will even get an official bill for the amount.

**Comment by Weedshaker** [comment]
sure, so do you have a 100% functional version at hand?

**Comment by Weedshaker** [comment]
and if yes, could we have a look at it. Also, let us know how much you expect?

**Comment by Bunnyfield** [comment]
Actually donations are not tied to a certain amount of money or work load but meant as a kind of acknowledgement for voluntary Open Source work, so it depends on you, how much you think it is worth for you. This is how we were able to work on version 5.0 which is has been refactored to be compatible to CMS 6.2 and at the same time to follow the namespaced sitepackage guidelines so we can use it as a base for version 7.0 now. The whole process was sponsored by several users and companies beforehand.

As mentioned before, full CMS 7 compatibility is still WIP, so we don't have a 100% version at hand yet. Things that are ready to be tested will be pushed to Github, so everybody can test them, and we highly appreciate feedback about your current problems as well, since we need information from real life users' workflows.

**Comment by Weedshaker** [comment]
THX for your effort!

**Comment by mbrodala** [comment]
@Bunnyfield Is there anything we can do to help you get this fixed soonish? :-)

**Comment by Bunnyfield** [comment]
@mbrodala Well - since I am already on it and things do look quite promising, currently sponsoring would be the best thing to speed things up. It will give me the option to focus even more on l10nmgr tasks instead of other things I have to do to make a living. Sponsors will get official bills for sponsored amounts.

And if it's just about motivating I have a wishlist on Amazon http://www.amazon.de/gp/registry/wishlist/2I80GX9ZSMYXX and currently my favorites would be made by Edradour ;-)

**Comment by johanneshahn** [comment]
i tried to fix it. but this extension must be written from scratch to work with v7 ?!

**Comment by mbrodala** [comment]
@Bunnyfield Sponsoring is an option for us, I'll get back to you after asking internally. :-)

**Comment by Bunnyfield** [comment]
@johanneshahn what makes you come to this conclusion? There are some things to be changed i.e. to register modules correctly and to respect new interface classes of the core - and of course the HTML-output must be adjusted to fit the new CMS 7 look and feel. But the main functionality does not have to be changed to make it run with CMS 7.

After making it run, we can start making it right, and in the end, when we will be compatible to PHP 7 as well, we can think about making it fast - so the CMS 8 compatible version will be partly rewritten, but definitely not written from scratch.

**Comment by johanneshahn** [comment]
i'm working on a Fork / currently a working local branch. the Backend Modul integration is completely outdated. I started rewriting it the extbase way with real templates etc. Domain/Model and Controllers. Some low Level functions and translation files are OK.

i think its cleaner to write it from scratch.

**Comment by Bunnyfield** [comment]
Well - it's up to you, if you think this is a good idea.

Just some thoughts:

1. Actually it is almost working here - we are testing stuff and despite some minor problems it seems to work out
2. Rewriting it with extbase is a complete no go, since we already got serious performance problems with larger translations in the current l10nmgr and extbase will make things even worse there
3. Why fork stuff if we can work together on the current state - IMHO it would be a waste of time if several people are working on different forks of the same extension
4. You could join the team on forge instead and check with Daniel Zielinski and myself how we could share the workload

**Comment by johanneshahn** [comment]
ur right! its better to work together and not to fork. 
i would help u testing things on branch 7 :+1:  ...

**Comment by Bunnyfield** [comment]
Cool - I guess I will be able to push the latest set of commits until tomorrow. First I have to take care of the 5-0 branch though, since Daniel is going to officially publish it to the TER.

**Comment by Bunnyfield** [comment]
Done :-)

https://typo3.org/extensions/repository/view/l10nmgr

Continuing with CMS 7 compatible master branch now - Official Git Repo with Gerrit review is under way as well.

**Comment by Bunnyfield** [comment]
Hmm - Did anyone already test the state I pushed last week?

**Comment by Weedshaker** [comment]
That was for the 5-0 branch, means typo3 6-6.99 right?
Let me know when you have the master branch for typo3 7-7.99 and I test it right away!

**Comment by sunixzs** [comment]
@Weedshaker : The current master is version 7: https://github.com/Bunnyfield/l10nmgr/blob/master/ext_emconf.php

**Comment by Bunnyfield** [comment]
Exactly - 5-0 has been branched for CMS 6.2 support - master is on CMS 7 compatibility already. Still WIP but major functionality should be working.

**Comment by mbrodala** [comment]
@Bunnyfield I've asked my colleague to check the latest state.

**Comment by mbrodala** [comment]
@Bunnyfield My colleague said that the import fails on content elements without headers. I'll try to get him into this ticket to avoid further delays.

**Comment by Bunnyfield** [comment]
@mbrodala Actually the import should not care about empty headers, but the export did. IIRC this has been fixed especially due to containers, since many people use them without providing a header.

**Comment by mbrodala** [comment]
@Bunnyfield I see. Does this mean we should do another export first, then re-try importing?

**Comment by Bunnyfield** [comment]
Older than a month now

**Comment by mbrodala** [comment]
@Bunnyfield Do you have a hint for my question? ;-)
