### ISSUE TITLE
No class named Tcemain

### ISSUE THREAD

**Issue by Shentao83** [Bunnyfield/l10nmgr#6]
Hi, I have Typ3 6.2.6 with PHP 5.5.9 running L10Nmgr 5.0. 

Everything seems to be working fine, but when I install the L10Nmgr and then click through the page tree, I constantly receive the Error Tabs with the error 

> TYPO3\CMS\Core\Utility\GeneralUtility::callUserFunction
> |No class named Tcemain|

and I have to close them individually or rightclick and then click on "Close All Tabs". Do you have any idea or hint what might cause this problem? I tried to google this error message, but found nothing that I might connect to the L10Nmgr. 

![error-l10nmgr](https://cloud.githubusercontent.com/assets/4661712/14608251/3e5c4742-0585-11e6-8fc7-b026b3bba2d4.PNG)

**Comment by Bunnyfield** [comment]
Could you please check, if l10nmgr/Classes/Hooks/Tcemain.php does exist with exactly that path on your machine, since this should provide the Tcemain class? - Please check upper and lower case letters as well, since it might be a problem with the file system you are using and file name refactoring.

I tested l10nmgr 5.0 on a freshly upgraded THEMES testing server and don't see the error.

BTW: Additionally it would be highly recommended to upgrade your TYPO3 to 6.2.21.

**Comment by Shentao83** [comment]
This is really strange, Tcemain.php really does exist under that exact path. When I rename that file to "tcemain.php" or any other name, the backend throws an uncaught exception which leads me to the assumption, that the file is indeed being found correctly. The server does generally make a difference between upper and lower case letters, so your assumption was indeed correct. 

Could it be another extension somehow overriding/altering Tcemain? 

I just checked the Typo3-Version, it is indeed 6.2.21 - the x.6 was a typo, propably because of 7.6 on another server. 

Oh, and btw. we have a 7.6.5 installation on the same server and the Github-version of l10nmgr works there flawlessly. Strange. I will try to uninstall other extensions in hopes to find the problem.


![tcemain](https://cloud.githubusercontent.com/assets/4661712/14632966/ac6d94fc-061b-11e6-9b36-c1b32189cd29.PNG)
