### ISSUE TITLE
Import: Relation parent check does not work

### ISSUE THREAD

**Issue by robert-heinig** [Bunnyfield/l10nmgr#7]
TYPO3: 7.6.6
l10nmgr: current master (last commit on Mar 13, 2016)
gridelements: 7.0.5

The nice feature do check relation parents resursively and to handle their localization did not work for me when exporting and importing to create new pages and CEs in another language.
I had to modify
L10nBaseService::recursivelyCheckForRelationParents()
to make it work, see
https://gist.github.com/robert-heinig/92b2dbcfdf3efd4c2e1f76d9d3a235e5

This is tested only for the gridelements usecase for creating new elements, not for updating or importing as default language. When I have more time I will also test the other usecases.

It's not an easy topic - as far as I'm able to comprehend what this method is supposed to do, I changed the following things:

- (1) This method should not be executed when $element[$parentField] is 0, because the SQL query will match for unrelated elements (l18n_parent = 0). The "if" regarding $element[$parentField] in the original method now is obsolete.
- (2) As a consequence of (1) the "localize" command should localize the checked parent, not the current element.
- (3) The elements to localize have to be localized from outer to inner - therefore the UID of the parent element has to be prepended and not appended in the command array.

As I'm writing this I think the checked element cache also should use the parent UID and not the UID of the current element.

Maybe this helps to make l10nmgr ready for TYPO3 CMS 7 LTS.

**Comment by Bunnyfield** [comment]
Well - the point is that the cmdmap should localize the outermost container only and skip all the inner elements, since they will be localized automatically when the outermost container gets localized.

After that, the datamap will step in and deliver the translated data to the localized elements.

So it should not matter at all, if the UID is prepended or appended, since it has to be the only UID of that particular container family tree anyway.

**Comment by Bunnyfield** [comment]
A bit more precisely:

As soon as there will be a translated container in the chain of possible containers, this must be the one that will get the "localizeSynchronize" command, since it will automatically do the job of translating it's children and all related trees.

Only if there is still no possible parent container left after checking for translated parents, the outermost container must get the "localize" command, since this will trigger the first set of localized copies for the whole family.

**Comment by Bunnyfield** [comment]
My conclusion:
1) Must not be checked, since the method is called after checking anyway, but still it would not hurt to do so
2) This is already done - in the family tree of the child there either will be a translated parent to be synchronized, or there will be a non translated parent to be localized
3) This is the actual bug, so the line should be
```
else {
    $this->TCEmain_cmd['tt_content'][$element[$parentField]]['localize'] = $Tlang;
}
```

**Comment by Bunnyfield** [comment]
Actually 3) is correct as well, since either there is a "grandparent" record available for that parent record, which triggers the recursive call, or the parent itself has to be translated - so it is always a container that will get the "localize" command

**Comment by Bunnyfield** [comment]
Any news on this one, or can I close that issue?

**Comment by robert-heinig** [comment]
Sorry for the late response.
You are right, it works just fine and I have no idea why it didn't work when i first tried it.
